/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HW1;

import java.awt.Color;
import java.io.IOException;
import java.net.SocketException;


/**
 *
 * @author Moaaz
 */
public class ClientUI extends javax.swing.JFrame {

    UDP_Client client;
    /**
     * Creates new form ClientUI
     */
    public ClientUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneMessage = new javax.swing.JTextPane();
        jButtonSendMessage = new javax.swing.JButton();
        jLabelIP = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldIP = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonOpenSocket = new javax.swing.JButton();
        jLabelHistory = new javax.swing.JLabel();
        jButtonCloseSocket = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneHistory = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelName.setText("Client Name");

        jScrollPane2.setViewportView(jTextPaneMessage);

        jButtonSendMessage.setText("Send Message");
        jButtonSendMessage.setToolTipText("");
        jButtonSendMessage.setEnabled(false);
        jButtonSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMessageActionPerformed(evt);
            }
        });

        jLabelIP.setText("IP:");

        jLabelPort.setText("Port:");

        jTextFieldIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldIP.setText("localhost");
        jTextFieldIP.setToolTipText("Port Number");

        jTextFieldPort.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPort.setText("44444");
        jTextFieldPort.setToolTipText("Port Number");

        jButtonOpenSocket.setText("Open Socket");
        jButtonOpenSocket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenSocketActionPerformed(evt);
            }
        });

        jLabelHistory.setText("History:");

        jButtonCloseSocket.setText("Close Socket");
        jButtonCloseSocket.setEnabled(false);
        jButtonCloseSocket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseSocketActionPerformed(evt);
            }
        });

        jTextPaneHistory.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabelHistory)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPort)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPort))
                            .addComponent(jButtonOpenSocket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCloseSocket, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSendMessage)
                            .addComponent(jLabelName))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHistory))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonOpenSocket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCloseSocket)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMessageActionPerformed
        
        String message = jTextPaneMessage.getText();
        // clear message
        jTextPaneMessage.setText("");
        if (!message.isEmpty()) {
            this.client.clientThread.sendMessage(message, this.client.clientThread.port,
                    this.client.clientThread.IPAddress, this.client.clientThread.clientSocket);
        }
    }//GEN-LAST:event_jButtonSendMessageActionPerformed

    private void jButtonOpenSocketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenSocketActionPerformed
        try {
            String host = jTextFieldIP.getText();
            int port = Integer.parseInt(jTextFieldPort.getText());
            
            client = new UDP_Client();
            client.start(host, port, jTextPaneHistory, jLabelName);
            disableOpenSocketButton();
        } catch (SocketException ex) {
            System.out.println("Error - jButtonOpenSocketActionPerformed : " + ex);
            enableOpenSocketButton();
        }
    }//GEN-LAST:event_jButtonOpenSocketActionPerformed

    private void jButtonCloseSocketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseSocketActionPerformed
        try {
            client.closeSocket();
            enableOpenSocketButton();
        } catch (IOException ex) {
            System.out.println("Error - jButtonCloseSocketActionPerformed : " + ex);
        }
    }//GEN-LAST:event_jButtonCloseSocketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseSocket;
    private javax.swing.JButton jButtonOpenSocket;
    private javax.swing.JButton jButtonSendMessage;
    private javax.swing.JLabel jLabelHistory;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldIP;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextPane jTextPaneHistory;
    private javax.swing.JTextPane jTextPaneMessage;
    // End of variables declaration//GEN-END:variables
    
        private void disableOpenSocketButton() {
        jButtonOpenSocket.setEnabled(false);
        jButtonCloseSocket.setEnabled(true);
        jButtonSendMessage.setEnabled(true);
    }

    private void enableOpenSocketButton() {
        jButtonOpenSocket.setEnabled(true);
        jButtonCloseSocket.setEnabled(false);
        jButtonSendMessage.setEnabled(false);
//        jButtonSendObject.setEnabled(false);
    }
}
